### PR TITLE
fixes #59, baseurl to resolve // issue

### LINKED ISSUE #59: Having a baseurl of '' doesnt work
An empty base url is recommended for jekyll hosted at the root of the site but this causes most of the links to break. 
Using '/' makes things mostly work, but there are a few places which result in a // inside the URL (such as inside the feed.xml, and when doing things with plugins like `jekyll-redirect-from`.

This article has some really good instructions on how to do baseurl stuff.
http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/

### PR DESCRIPTION
**Pull request by lukemcgregor**
Applied the ruleset for baseurls outlined here

http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/

### CODE REVIEW

**Comment by twitchett** [comment]
Hey, thanks a bunch for this fix, it's exactly what I needed. I had my baseurl set to `''` a lot of things were broken. Works perfectly now.

**Comment by lukemcgregor** [comment]
No problem glad it helped :)

**Comment by joshgerdes** [comment]
Not sure what's going on with this PR but seems like you should not need this many commits or changes to fix this possible issue. Closing, feel free to reopen if you have a specific issues to fix.

**Comment by lukemcgregor** [comment]
hang on @joshgerdes  i just broke it 5 mins ago, about to unbreak

**Pull request closed without merging**
